// Made by scripts/currencies.mjs from ICU and zone.tab; do not edit by hand.
// fixtures/currencies.json is the same data, for the phone and the tests.

export const currencyData = [
  {
    "code": "AED",
    "minorUnits": 2,
    "symbol": "AED",
    "en": "United Arab Emirates Dirham",
    "ar": "درهم إماراتي"
  },
  {
    "code": "AFN",
    "minorUnits": 0,
    "symbol": "؋",
    "en": "Afghan Afghani",
    "ar": "أفغاني"
  },
  {
    "code": "ALL",
    "minorUnits": 0,
    "symbol": "ALL",
    "en": "Albanian Lek",
    "ar": "ليك ألباني"
  },
  {
    "code": "AMD",
    "minorUnits": 2,
    "symbol": "֏",
    "en": "Armenian Dram",
    "ar": "درام أرميني"
  },
  {
    "code": "ANG",
    "minorUnits": 2,
    "symbol": "ANG",
    "en": "Netherlands Antillean Guilder",
    "ar": "غيلدر أنتيلي هولندي"
  },
  {
    "code": "AOA",
    "minorUnits": 2,
    "symbol": "Kz",
    "en": "Angolan Kwanza",
    "ar": "كوانزا أنغولي"
  },
  {
    "code": "ARS",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Argentine Peso",
    "ar": "بيزو أرجنتيني"
  },
  {
    "code": "AUD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Australian Dollar",
    "ar": "دولار أسترالي"
  },
  {
    "code": "AWG",
    "minorUnits": 2,
    "symbol": "AWG",
    "en": "Aruban Florin",
    "ar": "فلورن أروبي"
  },
  {
    "code": "AZN",
    "minorUnits": 2,
    "symbol": "₼",
    "en": "Azerbaijani Manat",
    "ar": "مانات أذربيجان"
  },
  {
    "code": "BAM",
    "minorUnits": 2,
    "symbol": "KM",
    "en": "Bosnia-Herzegovina Convertible Mark",
    "ar": "مارك البوسنة والهرسك قابل للتحويل"
  },
  {
    "code": "BBD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Barbadian Dollar",
    "ar": "دولار بربادوسي"
  },
  {
    "code": "BDT",
    "minorUnits": 2,
    "symbol": "৳",
    "en": "Bangladeshi Taka",
    "ar": "تاكا بنغلاديشي"
  },
  {
    "code": "BGN",
    "minorUnits": 2,
    "symbol": "BGN",
    "en": "Bulgarian Lev",
    "ar": "ليف بلغاري"
  },
  {
    "code": "BHD",
    "minorUnits": 3,
    "symbol": "BHD",
    "en": "Bahraini Dinar",
    "ar": "دينار بحريني"
  },
  {
    "code": "BIF",
    "minorUnits": 0,
    "symbol": "BIF",
    "en": "Burundian Franc",
    "ar": "فرنك بروندي"
  },
  {
    "code": "BMD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Bermudan Dollar",
    "ar": "دولار برمودي"
  },
  {
    "code": "BND",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Brunei Dollar",
    "ar": "دولار بروناي"
  },
  {
    "code": "BOB",
    "minorUnits": 2,
    "symbol": "Bs",
    "en": "Bolivian Boliviano",
    "ar": "بوليفيانو بوليفي"
  },
  {
    "code": "BRL",
    "minorUnits": 2,
    "symbol": "R$",
    "en": "Brazilian Real",
    "ar": "ريال برازيلي"
  },
  {
    "code": "BSD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Bahamian Dollar",
    "ar": "دولار باهامي"
  },
  {
    "code": "BTN",
    "minorUnits": 2,
    "symbol": "BTN",
    "en": "Bhutanese Ngultrum",
    "ar": "نولتوم بوتاني"
  },
  {
    "code": "BWP",
    "minorUnits": 2,
    "symbol": "P",
    "en": "Botswanan Pula",
    "ar": "بولا بتسواني"
  },
  {
    "code": "BYN",
    "minorUnits": 2,
    "symbol": "BYN",
    "en": "Belarusian Ruble",
    "ar": "روبل بيلاروسي"
  },
  {
    "code": "BZD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Belize Dollar",
    "ar": "دولار بليزي"
  },
  {
    "code": "CAD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Canadian Dollar",
    "ar": "دولار كندي"
  },
  {
    "code": "CDF",
    "minorUnits": 2,
    "symbol": "CDF",
    "en": "Congolese Franc",
    "ar": "فرنك كونغولي"
  },
  {
    "code": "CHF",
    "minorUnits": 2,
    "symbol": "CHF",
    "en": "Swiss Franc",
    "ar": "فرنك سويسري"
  },
  {
    "code": "CLP",
    "minorUnits": 0,
    "symbol": "$",
    "en": "Chilean Peso",
    "ar": "بيزو تشيلي"
  },
  {
    "code": "CNY",
    "minorUnits": 2,
    "symbol": "¥",
    "en": "Chinese Yuan",
    "ar": "يوان صيني"
  },
  {
    "code": "COP",
    "minorUnits": 0,
    "symbol": "$",
    "en": "Colombian Peso",
    "ar": "بيزو كولومبي"
  },
  {
    "code": "CRC",
    "minorUnits": 2,
    "symbol": "₡",
    "en": "Costa Rican Colón",
    "ar": "كولن كوستاريكي"
  },
  {
    "code": "CUC",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Cuban Convertible Peso",
    "ar": "بيزو كوبي قابل للتحويل"
  },
  {
    "code": "CUP",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Cuban Peso",
    "ar": "بيزو كوبي"
  },
  {
    "code": "CVE",
    "minorUnits": 2,
    "symbol": "CVE",
    "en": "Cape Verdean Escudo",
    "ar": "اسكودو الرأس الأخضر"
  },
  {
    "code": "CZK",
    "minorUnits": 2,
    "symbol": "Kč",
    "en": "Czech Koruna",
    "ar": "كرونة تشيكية"
  },
  {
    "code": "DJF",
    "minorUnits": 0,
    "symbol": "DJF",
    "en": "Djiboutian Franc",
    "ar": "فرنك جيبوتي"
  },
  {
    "code": "DKK",
    "minorUnits": 2,
    "symbol": "kr",
    "en": "Danish Krone",
    "ar": "كرونة دنماركية"
  },
  {
    "code": "DOP",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Dominican Peso",
    "ar": "بيزو الدومنيكان"
  },
  {
    "code": "DZD",
    "minorUnits": 2,
    "symbol": "DA",
    "en": "Algerian Dinar",
    "ar": "دينار جزائري"
  },
  {
    "code": "EGP",
    "minorUnits": 2,
    "symbol": "E£",
    "en": "Egyptian Pound",
    "ar": "جنيه مصري"
  },
  {
    "code": "ERN",
    "minorUnits": 2,
    "symbol": "ERN",
    "en": "Eritrean Nakfa",
    "ar": "ناكفا أريتري"
  },
  {
    "code": "ETB",
    "minorUnits": 2,
    "symbol": "ETB",
    "en": "Ethiopian Birr",
    "ar": "بير أثيوبي"
  },
  {
    "code": "EUR",
    "minorUnits": 2,
    "symbol": "€",
    "en": "Euro",
    "ar": "يورو"
  },
  {
    "code": "FJD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Fijian Dollar",
    "ar": "دولار فيجي"
  },
  {
    "code": "FKP",
    "minorUnits": 2,
    "symbol": "£",
    "en": "Falkland Islands Pound",
    "ar": "جنيه جزر فوكلاند"
  },
  {
    "code": "GBP",
    "minorUnits": 2,
    "symbol": "£",
    "en": "British Pound",
    "ar": "جنيه إسترليني"
  },
  {
    "code": "GEL",
    "minorUnits": 2,
    "symbol": "₾",
    "en": "Georgian Lari",
    "ar": "لارى جورجي"
  },
  {
    "code": "GHS",
    "minorUnits": 2,
    "symbol": "GH₵",
    "en": "Ghanaian Cedi",
    "ar": "سيدي غانا"
  },
  {
    "code": "GIP",
    "minorUnits": 2,
    "symbol": "£",
    "en": "Gibraltar Pound",
    "ar": "جنيه جبل طارق"
  },
  {
    "code": "GMD",
    "minorUnits": 2,
    "symbol": "GMD",
    "en": "Gambian Dalasi",
    "ar": "دلاسي غامبي"
  },
  {
    "code": "GNF",
    "minorUnits": 0,
    "symbol": "FG",
    "en": "Guinean Franc",
    "ar": "فرنك غينيا"
  },
  {
    "code": "GTQ",
    "minorUnits": 2,
    "symbol": "Q",
    "en": "Guatemalan Quetzal",
    "ar": "كوتزال غواتيمالا"
  },
  {
    "code": "GYD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Guyanaese Dollar",
    "ar": "دولار غيانا"
  },
  {
    "code": "HKD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Hong Kong Dollar",
    "ar": "دولار هونغ كونغ"
  },
  {
    "code": "HNL",
    "minorUnits": 2,
    "symbol": "L",
    "en": "Honduran Lempira",
    "ar": "ليمبيرا هنداروس"
  },
  {
    "code": "HRK",
    "minorUnits": 2,
    "symbol": "kn",
    "en": "Croatian Kuna",
    "ar": "كونا كرواتي"
  },
  {
    "code": "HTG",
    "minorUnits": 2,
    "symbol": "HTG",
    "en": "Haitian Gourde",
    "ar": "جوردى هايتي"
  },
  {
    "code": "HUF",
    "minorUnits": 0,
    "symbol": "Ft",
    "en": "Hungarian Forint",
    "ar": "فورينت هنغاري"
  },
  {
    "code": "IDR",
    "minorUnits": 0,
    "symbol": "Rp",
    "en": "Indonesian Rupiah",
    "ar": "روبية إندونيسية"
  },
  {
    "code": "ILS",
    "minorUnits": 2,
    "symbol": "₪",
    "en": "Israeli New Shekel",
    "ar": "شيكل إسرائيلي جديد"
  },
  {
    "code": "INR",
    "minorUnits": 2,
    "symbol": "₹",
    "en": "Indian Rupee",
    "ar": "روبية هندي"
  },
  {
    "code": "IQD",
    "minorUnits": 0,
    "symbol": "IQD",
    "en": "Iraqi Dinar",
    "ar": "دينار عراقي"
  },
  {
    "code": "IRR",
    "minorUnits": 0,
    "symbol": "IRR",
    "en": "Iranian Rial",
    "ar": "ريال إيراني"
  },
  {
    "code": "ISK",
    "minorUnits": 0,
    "symbol": "kr",
    "en": "Icelandic Króna",
    "ar": "كرونة أيسلندية"
  },
  {
    "code": "JMD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Jamaican Dollar",
    "ar": "دولار جامايكي"
  },
  {
    "code": "JOD",
    "minorUnits": 3,
    "symbol": "JOD",
    "en": "Jordanian Dinar",
    "ar": "دينار أردني"
  },
  {
    "code": "JPY",
    "minorUnits": 0,
    "symbol": "¥",
    "en": "Japanese Yen",
    "ar": "ين ياباني"
  },
  {
    "code": "KES",
    "minorUnits": 2,
    "symbol": "KES",
    "en": "Kenyan Shilling",
    "ar": "شلن كينيي"
  },
  {
    "code": "KGS",
    "minorUnits": 2,
    "symbol": "⃀",
    "en": "Kyrgyz Som",
    "ar": "سوم قيرغستاني"
  },
  {
    "code": "KHR",
    "minorUnits": 2,
    "symbol": "៛",
    "en": "Cambodian Riel",
    "ar": "رييال كمبودي"
  },
  {
    "code": "KMF",
    "minorUnits": 0,
    "symbol": "CF",
    "en": "Comorian Franc",
    "ar": "فرنك جزر القمر"
  },
  {
    "code": "KPW",
    "minorUnits": 0,
    "symbol": "₩",
    "en": "North Korean Won",
    "ar": "وون كوريا الشمالية"
  },
  {
    "code": "KRW",
    "minorUnits": 0,
    "symbol": "₩",
    "en": "South Korean Won",
    "ar": "وون كوريا الجنوبية"
  },
  {
    "code": "KWD",
    "minorUnits": 3,
    "symbol": "KWD",
    "en": "Kuwaiti Dinar",
    "ar": "دينار كويتي"
  },
  {
    "code": "KYD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Cayman Islands Dollar",
    "ar": "دولار جزر كيمن"
  },
  {
    "code": "KZT",
    "minorUnits": 2,
    "symbol": "₸",
    "en": "Kazakhstani Tenge",
    "ar": "تينغ كازاخستاني"
  },
  {
    "code": "LAK",
    "minorUnits": 0,
    "symbol": "₭",
    "en": "Laotian Kip",
    "ar": "كيب لاوسي"
  },
  {
    "code": "LBP",
    "minorUnits": 0,
    "symbol": "L£",
    "en": "Lebanese Pound",
    "ar": "جنيه لبناني"
  },
  {
    "code": "LKR",
    "minorUnits": 2,
    "symbol": "Rs",
    "en": "Sri Lankan Rupee",
    "ar": "روبية سريلانكية"
  },
  {
    "code": "LRD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Liberian Dollar",
    "ar": "دولار ليبيري"
  },
  {
    "code": "LSL",
    "minorUnits": 2,
    "symbol": "LSL",
    "en": "Lesotho Loti",
    "ar": "لوتي ليسوتو"
  },
  {
    "code": "LYD",
    "minorUnits": 3,
    "symbol": "LYD",
    "en": "Libyan Dinar",
    "ar": "دينار ليبي"
  },
  {
    "code": "MAD",
    "minorUnits": 2,
    "symbol": "DH",
    "en": "Moroccan Dirham",
    "ar": "درهم مغربي"
  },
  {
    "code": "MDL",
    "minorUnits": 2,
    "symbol": "MDL",
    "en": "Moldovan Leu",
    "ar": "ليو مولدوفي"
  },
  {
    "code": "MGA",
    "minorUnits": 0,
    "symbol": "Ar",
    "en": "Malagasy Ariary",
    "ar": "أرياري مدغشقر"
  },
  {
    "code": "MKD",
    "minorUnits": 2,
    "symbol": "MKD",
    "en": "Macedonian Denar",
    "ar": "دينار مقدوني"
  },
  {
    "code": "MMK",
    "minorUnits": 0,
    "symbol": "K",
    "en": "Myanmar Kyat",
    "ar": "كيات ميانمار"
  },
  {
    "code": "MNT",
    "minorUnits": 2,
    "symbol": "₮",
    "en": "Mongolian Tugrik",
    "ar": "توغروغ منغولي"
  },
  {
    "code": "MOP",
    "minorUnits": 2,
    "symbol": "MOP",
    "en": "Macanese Pataca",
    "ar": "باتاكا ماكاوي"
  },
  {
    "code": "MRU",
    "minorUnits": 2,
    "symbol": "MRU",
    "en": "Mauritanian Ouguiya",
    "ar": "أوقية موريتانية"
  },
  {
    "code": "MUR",
    "minorUnits": 2,
    "symbol": "Rs",
    "en": "Mauritian Rupee",
    "ar": "روبية موريشيوسية"
  },
  {
    "code": "MVR",
    "minorUnits": 2,
    "symbol": "MVR",
    "en": "Maldivian Rufiyaa",
    "ar": "روفيه جزر المالديف"
  },
  {
    "code": "MWK",
    "minorUnits": 2,
    "symbol": "MWK",
    "en": "Malawian Kwacha",
    "ar": "كواشا مالاوي"
  },
  {
    "code": "MXN",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Mexican Peso",
    "ar": "بيزو مكسيكي"
  },
  {
    "code": "MYR",
    "minorUnits": 2,
    "symbol": "RM",
    "en": "Malaysian Ringgit",
    "ar": "رينغيت ماليزي"
  },
  {
    "code": "MZN",
    "minorUnits": 2,
    "symbol": "MZN",
    "en": "Mozambican Metical",
    "ar": "متكال موزمبيقي"
  },
  {
    "code": "NAD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Namibian Dollar",
    "ar": "دولار ناميبي"
  },
  {
    "code": "NGN",
    "minorUnits": 2,
    "symbol": "₦",
    "en": "Nigerian Naira",
    "ar": "نايرا نيجيري"
  },
  {
    "code": "NIO",
    "minorUnits": 2,
    "symbol": "C$",
    "en": "Nicaraguan Córdoba",
    "ar": "قرطبة نيكاراغوا"
  },
  {
    "code": "NOK",
    "minorUnits": 2,
    "symbol": "kr",
    "en": "Norwegian Krone",
    "ar": "كرونة نرويجية"
  },
  {
    "code": "NPR",
    "minorUnits": 2,
    "symbol": "Rs",
    "en": "Nepalese Rupee",
    "ar": "روبية نيبالي"
  },
  {
    "code": "NZD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "New Zealand Dollar",
    "ar": "دولار نيوزيلندي"
  },
  {
    "code": "OMR",
    "minorUnits": 3,
    "symbol": "OMR",
    "en": "Omani Rial",
    "ar": "ريال عماني"
  },
  {
    "code": "PAB",
    "minorUnits": 2,
    "symbol": "PAB",
    "en": "Panamanian Balboa",
    "ar": "بالبوا بنمي"
  },
  {
    "code": "PEN",
    "minorUnits": 2,
    "symbol": "PEN",
    "en": "Peruvian Sol",
    "ar": "سول بيروفي"
  },
  {
    "code": "PGK",
    "minorUnits": 2,
    "symbol": "PGK",
    "en": "Papua New Guinean Kina",
    "ar": "كينا بابوا غينيا الجديدة"
  },
  {
    "code": "PHP",
    "minorUnits": 2,
    "symbol": "₱",
    "en": "Philippine Peso",
    "ar": "بيزو فلبيني"
  },
  {
    "code": "PKR",
    "minorUnits": 0,
    "symbol": "Rs",
    "en": "Pakistani Rupee",
    "ar": "روبية باكستاني"
  },
  {
    "code": "PLN",
    "minorUnits": 2,
    "symbol": "zł",
    "en": "Polish Zloty",
    "ar": "زلوتي بولندي"
  },
  {
    "code": "PYG",
    "minorUnits": 0,
    "symbol": "₲",
    "en": "Paraguayan Guarani",
    "ar": "غواراني باراغواي"
  },
  {
    "code": "QAR",
    "minorUnits": 2,
    "symbol": "QAR",
    "en": "Qatari Riyal",
    "ar": "ريال قطري"
  },
  {
    "code": "RON",
    "minorUnits": 2,
    "symbol": "lei",
    "en": "Romanian Leu",
    "ar": "ليو روماني"
  },
  {
    "code": "RSD",
    "minorUnits": 2,
    "symbol": "RSD",
    "en": "Serbian Dinar",
    "ar": "دينار صربي"
  },
  {
    "code": "RUB",
    "minorUnits": 2,
    "symbol": "₽",
    "en": "Russian Ruble",
    "ar": "روبل روسي"
  },
  {
    "code": "RWF",
    "minorUnits": 0,
    "symbol": "RF",
    "en": "Rwandan Franc",
    "ar": "فرنك رواندي"
  },
  {
    "code": "SAR",
    "minorUnits": 2,
    "symbol": "SR",
    "en": "Saudi Riyal",
    "ar": "ريال سعودي"
  },
  {
    "code": "SBD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Solomon Islands Dollar",
    "ar": "دولار جزر سليمان"
  },
  {
    "code": "SCR",
    "minorUnits": 2,
    "symbol": "SCR",
    "en": "Seychellois Rupee",
    "ar": "روبية سيشيلية"
  },
  {
    "code": "SDG",
    "minorUnits": 2,
    "symbol": "SDG",
    "en": "Sudanese Pound",
    "ar": "جنيه سوداني"
  },
  {
    "code": "SEK",
    "minorUnits": 2,
    "symbol": "kr",
    "en": "Swedish Krona",
    "ar": "كرونة سويدية"
  },
  {
    "code": "SGD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Singapore Dollar",
    "ar": "دولار سنغافوري"
  },
  {
    "code": "SHP",
    "minorUnits": 2,
    "symbol": "£",
    "en": "St. Helena Pound",
    "ar": "جنيه سانت هيلين"
  },
  {
    "code": "SLE",
    "minorUnits": 2,
    "symbol": "SLE",
    "en": "Sierra Leonean Leone",
    "ar": "ليون سيراليوني"
  },
  {
    "code": "SLL",
    "minorUnits": 0,
    "symbol": "SLL",
    "en": "Sierra Leonean Leone (1964—2022)",
    "ar": "ليون سيراليوني - 1964-2022"
  },
  {
    "code": "SOS",
    "minorUnits": 0,
    "symbol": "SOS",
    "en": "Somali Shilling",
    "ar": "شلن صومالي"
  },
  {
    "code": "SRD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Surinamese Dollar",
    "ar": "دولار سورينامي"
  },
  {
    "code": "SSP",
    "minorUnits": 2,
    "symbol": "£",
    "en": "South Sudanese Pound",
    "ar": "جنيه جنوب السودان"
  },
  {
    "code": "STN",
    "minorUnits": 2,
    "symbol": "Db",
    "en": "São Tomé & Príncipe Dobra",
    "ar": "دوبرا ساو تومي وبرينسيبي"
  },
  {
    "code": "SVC",
    "minorUnits": 2,
    "symbol": "SVC",
    "en": "Salvadoran Colón",
    "ar": "كولون سلفادوري"
  },
  {
    "code": "SYP",
    "minorUnits": 0,
    "symbol": "£",
    "en": "Syrian Pound",
    "ar": "ليرة سورية"
  },
  {
    "code": "SZL",
    "minorUnits": 2,
    "symbol": "SZL",
    "en": "Swazi Lilangeni",
    "ar": "ليلانجيني سوازيلندي"
  },
  {
    "code": "THB",
    "minorUnits": 2,
    "symbol": "฿",
    "en": "Thai Baht",
    "ar": "باخت تايلاندي"
  },
  {
    "code": "TJS",
    "minorUnits": 2,
    "symbol": "TJS",
    "en": "Tajikistani Somoni",
    "ar": "سوموني طاجيكستاني"
  },
  {
    "code": "TMT",
    "minorUnits": 2,
    "symbol": "TMT",
    "en": "Turkmenistani Manat",
    "ar": "مانات تركمانستان"
  },
  {
    "code": "TND",
    "minorUnits": 3,
    "symbol": "DT",
    "en": "Tunisian Dinar",
    "ar": "دينار تونسي"
  },
  {
    "code": "TOP",
    "minorUnits": 2,
    "symbol": "T$",
    "en": "Tongan Paʻanga",
    "ar": "بانغا تونغا"
  },
  {
    "code": "TRY",
    "minorUnits": 2,
    "symbol": "₺",
    "en": "Turkish Lira",
    "ar": "ليرة تركية"
  },
  {
    "code": "TTD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Trinidad & Tobago Dollar",
    "ar": "دولار ترينداد وتوباغو"
  },
  {
    "code": "TWD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "New Taiwan Dollar",
    "ar": "دولار تايواني"
  },
  {
    "code": "TZS",
    "minorUnits": 2,
    "symbol": "TZS",
    "en": "Tanzanian Shilling",
    "ar": "شلن تنزاني"
  },
  {
    "code": "UAH",
    "minorUnits": 2,
    "symbol": "₴",
    "en": "Ukrainian Hryvnia",
    "ar": "هريفنيا أوكراني"
  },
  {
    "code": "UGX",
    "minorUnits": 0,
    "symbol": "UGX",
    "en": "Ugandan Shilling",
    "ar": "شلن أوغندي"
  },
  {
    "code": "USD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "US Dollar",
    "ar": "دولار أمريكي"
  },
  {
    "code": "UYU",
    "minorUnits": 2,
    "symbol": "$",
    "en": "Uruguayan Peso",
    "ar": "بيزو اوروغواي"
  },
  {
    "code": "UZS",
    "minorUnits": 2,
    "symbol": "UZS",
    "en": "Uzbekistani Som",
    "ar": "سوم أوزبكستاني"
  },
  {
    "code": "VES",
    "minorUnits": 2,
    "symbol": "VES",
    "en": "Venezuelan Bolívar",
    "ar": "بوليفار فنزويلي"
  },
  {
    "code": "VND",
    "minorUnits": 0,
    "symbol": "₫",
    "en": "Vietnamese Dong",
    "ar": "دونج فيتنامي"
  },
  {
    "code": "VUV",
    "minorUnits": 0,
    "symbol": "VUV",
    "en": "Vanuatu Vatu",
    "ar": "فاتو فانواتو"
  },
  {
    "code": "WST",
    "minorUnits": 2,
    "symbol": "WST",
    "en": "Samoan Tala",
    "ar": "تالا ساموا"
  },
  {
    "code": "XAF",
    "minorUnits": 0,
    "symbol": "FCFA",
    "en": "Central African CFA Franc",
    "ar": "فرنك وسط أفريقي"
  },
  {
    "code": "XCD",
    "minorUnits": 2,
    "symbol": "$",
    "en": "East Caribbean Dollar",
    "ar": "دولار شرق الكاريبي"
  },
  {
    "code": "XCG",
    "minorUnits": 2,
    "symbol": "Cg.",
    "en": "Caribbean guilder",
    "ar": "غيلدر كاريبي"
  },
  {
    "code": "XOF",
    "minorUnits": 0,
    "symbol": "F CFA",
    "en": "West African CFA Franc",
    "ar": "فرنك غرب أفريقي"
  },
  {
    "code": "XPF",
    "minorUnits": 0,
    "symbol": "CFPF",
    "en": "CFP Franc",
    "ar": "فرنك سي إف بي"
  },
  {
    "code": "YER",
    "minorUnits": 0,
    "symbol": "YER",
    "en": "Yemeni Rial",
    "ar": "ريال يمني"
  },
  {
    "code": "ZAR",
    "minorUnits": 2,
    "symbol": "R",
    "en": "South African Rand",
    "ar": "راند جنوب أفريقيا"
  },
  {
    "code": "ZMW",
    "minorUnits": 2,
    "symbol": "ZK",
    "en": "Zambian Kwacha",
    "ar": "كواشا زامبي"
  },
  {
    "code": "ZWG",
    "minorUnits": 2,
    "symbol": "ZWG",
    "en": "Zimbabwean Gold",
    "ar": "ذهب زيمبابوي"
  },
  {
    "code": "ZWL",
    "minorUnits": 2,
    "symbol": "ZWL",
    "en": "Zimbabwean Dollar (2009–2024)",
    "ar": "دولار زمبابوي 2009"
  }
] as const;

export const countryCurrencies: Readonly<Record<string, string>> = {
  "AD": "EUR",
  "AE": "AED",
  "AF": "AFN",
  "AG": "XCD",
  "AI": "XCD",
  "AL": "ALL",
  "AM": "AMD",
  "AO": "AOA",
  "AR": "ARS",
  "AS": "USD",
  "AT": "EUR",
  "AU": "AUD",
  "AW": "AWG",
  "AX": "EUR",
  "AZ": "AZN",
  "BA": "BAM",
  "BB": "BBD",
  "BD": "BDT",
  "BE": "EUR",
  "BF": "XOF",
  "BG": "BGN",
  "BH": "BHD",
  "BI": "BIF",
  "BJ": "XOF",
  "BL": "EUR",
  "BM": "BMD",
  "BN": "BND",
  "BO": "BOB",
  "BQ": "USD",
  "BR": "BRL",
  "BS": "BSD",
  "BT": "BTN",
  "BV": "NOK",
  "BW": "BWP",
  "BY": "BYN",
  "BZ": "BZD",
  "CA": "CAD",
  "CC": "AUD",
  "CD": "CDF",
  "CF": "XAF",
  "CG": "XAF",
  "CH": "CHF",
  "CI": "XOF",
  "CK": "NZD",
  "CL": "CLP",
  "CM": "XAF",
  "CN": "CNY",
  "CO": "COP",
  "CR": "CRC",
  "CU": "CUP",
  "CV": "CVE",
  "CW": "ANG",
  "CX": "AUD",
  "CY": "EUR",
  "CZ": "CZK",
  "DE": "EUR",
  "DJ": "DJF",
  "DK": "DKK",
  "DM": "XCD",
  "DO": "DOP",
  "DZ": "DZD",
  "EC": "USD",
  "EE": "EUR",
  "EG": "EGP",
  "EH": "MAD",
  "ER": "ERN",
  "ES": "EUR",
  "ET": "ETB",
  "FI": "EUR",
  "FJ": "FJD",
  "FK": "FKP",
  "FM": "USD",
  "FO": "DKK",
  "FR": "EUR",
  "GA": "XAF",
  "GB": "GBP",
  "GD": "XCD",
  "GE": "GEL",
  "GF": "EUR",
  "GG": "GBP",
  "GH": "GHS",
  "GI": "GIP",
  "GL": "DKK",
  "GM": "GMD",
  "GN": "GNF",
  "GP": "EUR",
  "GQ": "XAF",
  "GR": "EUR",
  "GS": "GBP",
  "GT": "GTQ",
  "GU": "USD",
  "GW": "XOF",
  "GY": "GYD",
  "HK": "HKD",
  "HM": "AUD",
  "HN": "HNL",
  "HR": "EUR",
  "HT": "HTG",
  "HU": "HUF",
  "ID": "IDR",
  "IE": "EUR",
  "IL": "ILS",
  "IM": "GBP",
  "IN": "INR",
  "IO": "USD",
  "IQ": "IQD",
  "IR": "IRR",
  "IS": "ISK",
  "IT": "EUR",
  "JE": "GBP",
  "JM": "JMD",
  "JO": "JOD",
  "JP": "JPY",
  "KE": "KES",
  "KG": "KGS",
  "KH": "KHR",
  "KI": "AUD",
  "KM": "KMF",
  "KN": "XCD",
  "KP": "KPW",
  "KR": "KRW",
  "KW": "KWD",
  "KY": "KYD",
  "KZ": "KZT",
  "LA": "LAK",
  "LB": "LBP",
  "LC": "XCD",
  "LI": "CHF",
  "LK": "LKR",
  "LR": "LRD",
  "LS": "LSL",
  "LT": "EUR",
  "LU": "EUR",
  "LV": "EUR",
  "LY": "LYD",
  "MA": "MAD",
  "MC": "EUR",
  "MD": "MDL",
  "ME": "EUR",
  "MF": "EUR",
  "MG": "MGA",
  "MH": "USD",
  "MK": "MKD",
  "ML": "XOF",
  "MM": "MMK",
  "MN": "MNT",
  "MO": "MOP",
  "MP": "USD",
  "MQ": "EUR",
  "MR": "MRU",
  "MS": "XCD",
  "MT": "EUR",
  "MU": "MUR",
  "MV": "MVR",
  "MW": "MWK",
  "MX": "MXN",
  "MY": "MYR",
  "MZ": "MZN",
  "NA": "NAD",
  "NC": "XPF",
  "NE": "XOF",
  "NF": "AUD",
  "NG": "NGN",
  "NI": "NIO",
  "NL": "EUR",
  "NO": "NOK",
  "NP": "NPR",
  "NR": "AUD",
  "NU": "NZD",
  "NZ": "NZD",
  "OM": "OMR",
  "PA": "PAB",
  "PE": "PEN",
  "PF": "XPF",
  "PG": "PGK",
  "PH": "PHP",
  "PK": "PKR",
  "PL": "PLN",
  "PM": "EUR",
  "PN": "NZD",
  "PR": "USD",
  "PS": "ILS",
  "PT": "EUR",
  "PW": "USD",
  "PY": "PYG",
  "QA": "QAR",
  "RE": "EUR",
  "RO": "RON",
  "RS": "RSD",
  "RU": "RUB",
  "RW": "RWF",
  "SA": "SAR",
  "SB": "SBD",
  "SC": "SCR",
  "SD": "SDG",
  "SE": "SEK",
  "SG": "SGD",
  "SH": "SHP",
  "SI": "EUR",
  "SJ": "NOK",
  "SK": "EUR",
  "SL": "SLE",
  "SM": "EUR",
  "SN": "XOF",
  "SO": "SOS",
  "SR": "SRD",
  "SS": "SSP",
  "ST": "STN",
  "SV": "USD",
  "SX": "ANG",
  "SY": "SYP",
  "SZ": "SZL",
  "TC": "USD",
  "TD": "XAF",
  "TF": "EUR",
  "TG": "XOF",
  "TH": "THB",
  "TJ": "TJS",
  "TK": "NZD",
  "TL": "USD",
  "TM": "TMT",
  "TN": "TND",
  "TO": "TOP",
  "TR": "TRY",
  "TT": "TTD",
  "TV": "AUD",
  "TW": "TWD",
  "TZ": "TZS",
  "UA": "UAH",
  "UG": "UGX",
  "UM": "USD",
  "US": "USD",
  "UY": "UYU",
  "UZ": "UZS",
  "VA": "EUR",
  "VC": "XCD",
  "VE": "VES",
  "VG": "USD",
  "VI": "USD",
  "VN": "VND",
  "VU": "VUV",
  "WF": "XPF",
  "WS": "WST",
  "XK": "EUR",
  "YE": "YER",
  "YT": "EUR",
  "ZA": "ZAR",
  "ZM": "ZMW",
  "ZW": "ZWG"
};

export const zoneCountries: Readonly<Record<string, string>> = {
  "Africa/Abidjan": "CI",
  "Africa/Accra": "GH",
  "Africa/Addis_Ababa": "ET",
  "Africa/Algiers": "DZ",
  "Africa/Asmara": "ER",
  "Africa/Asmera": "ER",
  "Africa/Bamako": "ML",
  "Africa/Bangui": "CF",
  "Africa/Banjul": "GM",
  "Africa/Bissau": "GW",
  "Africa/Blantyre": "MW",
  "Africa/Brazzaville": "CG",
  "Africa/Bujumbura": "BI",
  "Africa/Cairo": "EG",
  "Africa/Casablanca": "MA",
  "Africa/Ceuta": "ES",
  "Africa/Conakry": "GN",
  "Africa/Dakar": "SN",
  "Africa/Dar_es_Salaam": "TZ",
  "Africa/Djibouti": "DJ",
  "Africa/Douala": "CM",
  "Africa/El_Aaiun": "EH",
  "Africa/Freetown": "SL",
  "Africa/Gaborone": "BW",
  "Africa/Harare": "ZW",
  "Africa/Johannesburg": "ZA",
  "Africa/Juba": "SS",
  "Africa/Kampala": "UG",
  "Africa/Khartoum": "SD",
  "Africa/Kigali": "RW",
  "Africa/Kinshasa": "CD",
  "Africa/Lagos": "NG",
  "Africa/Libreville": "GA",
  "Africa/Lome": "TG",
  "Africa/Luanda": "AO",
  "Africa/Lubumbashi": "CD",
  "Africa/Lusaka": "ZM",
  "Africa/Malabo": "GQ",
  "Africa/Maputo": "MZ",
  "Africa/Maseru": "LS",
  "Africa/Mbabane": "SZ",
  "Africa/Mogadishu": "SO",
  "Africa/Monrovia": "LR",
  "Africa/Nairobi": "KE",
  "Africa/Ndjamena": "TD",
  "Africa/Niamey": "NE",
  "Africa/Nouakchott": "MR",
  "Africa/Ouagadougou": "BF",
  "Africa/Porto-Novo": "BJ",
  "Africa/Sao_Tome": "ST",
  "Africa/Tripoli": "LY",
  "Africa/Tunis": "TN",
  "Africa/Windhoek": "NA",
  "America/Adak": "US",
  "America/Anchorage": "US",
  "America/Anguilla": "AI",
  "America/Antigua": "AG",
  "America/Araguaina": "BR",
  "America/Argentina/Buenos_Aires": "AR",
  "America/Argentina/Catamarca": "AR",
  "America/Argentina/Cordoba": "AR",
  "America/Argentina/Jujuy": "AR",
  "America/Argentina/La_Rioja": "AR",
  "America/Argentina/Mendoza": "AR",
  "America/Argentina/Rio_Gallegos": "AR",
  "America/Argentina/Salta": "AR",
  "America/Argentina/San_Juan": "AR",
  "America/Argentina/San_Luis": "AR",
  "America/Argentina/Tucuman": "AR",
  "America/Argentina/Ushuaia": "AR",
  "America/Aruba": "AW",
  "America/Asuncion": "PY",
  "America/Atikokan": "CA",
  "America/Bahia": "BR",
  "America/Bahia_Banderas": "MX",
  "America/Barbados": "BB",
  "America/Belem": "BR",
  "America/Belize": "BZ",
  "America/Blanc-Sablon": "CA",
  "America/Boa_Vista": "BR",
  "America/Bogota": "CO",
  "America/Boise": "US",
  "America/Buenos_Aires": "AR",
  "America/Cambridge_Bay": "CA",
  "America/Campo_Grande": "BR",
  "America/Cancun": "MX",
  "America/Caracas": "VE",
  "America/Cayenne": "GF",
  "America/Cayman": "KY",
  "America/Chicago": "US",
  "America/Chihuahua": "MX",
  "America/Ciudad_Juarez": "MX",
  "America/Costa_Rica": "CR",
  "America/Coyhaique": "CL",
  "America/Creston": "CA",
  "America/Cuiaba": "BR",
  "America/Curacao": "CW",
  "America/Danmarkshavn": "GL",
  "America/Dawson": "CA",
  "America/Dawson_Creek": "CA",
  "America/Denver": "US",
  "America/Detroit": "US",
  "America/Dominica": "DM",
  "America/Edmonton": "CA",
  "America/Eirunepe": "BR",
  "America/El_Salvador": "SV",
  "America/Fort_Nelson": "CA",
  "America/Fortaleza": "BR",
  "America/Glace_Bay": "CA",
  "America/Goose_Bay": "CA",
  "America/Grand_Turk": "TC",
  "America/Grenada": "GD",
  "America/Guadeloupe": "GP",
  "America/Guatemala": "GT",
  "America/Guayaquil": "EC",
  "America/Guyana": "GY",
  "America/Halifax": "CA",
  "America/Havana": "CU",
  "America/Hermosillo": "MX",
  "America/Indiana/Indianapolis": "US",
  "America/Indiana/Knox": "US",
  "America/Indiana/Marengo": "US",
  "America/Indiana/Petersburg": "US",
  "America/Indiana/Tell_City": "US",
  "America/Indiana/Vevay": "US",
  "America/Indiana/Vincennes": "US",
  "America/Indiana/Winamac": "US",
  "America/Inuvik": "CA",
  "America/Iqaluit": "CA",
  "America/Jamaica": "JM",
  "America/Juneau": "US",
  "America/Kentucky/Louisville": "US",
  "America/Kentucky/Monticello": "US",
  "America/Kralendijk": "BQ",
  "America/La_Paz": "BO",
  "America/Lima": "PE",
  "America/Los_Angeles": "US",
  "America/Lower_Princes": "SX",
  "America/Maceio": "BR",
  "America/Managua": "NI",
  "America/Manaus": "BR",
  "America/Marigot": "MF",
  "America/Martinique": "MQ",
  "America/Matamoros": "MX",
  "America/Mazatlan": "MX",
  "America/Menominee": "US",
  "America/Merida": "MX",
  "America/Metlakatla": "US",
  "America/Mexico_City": "MX",
  "America/Miquelon": "PM",
  "America/Moncton": "CA",
  "America/Monterrey": "MX",
  "America/Montevideo": "UY",
  "America/Montserrat": "MS",
  "America/Nassau": "BS",
  "America/New_York": "US",
  "America/Nome": "US",
  "America/Noronha": "BR",
  "America/North_Dakota/Beulah": "US",
  "America/North_Dakota/Center": "US",
  "America/North_Dakota/New_Salem": "US",
  "America/Nuuk": "GL",
  "America/Ojinaga": "MX",
  "America/Panama": "PA",
  "America/Paramaribo": "SR",
  "America/Phoenix": "US",
  "America/Port-au-Prince": "HT",
  "America/Port_of_Spain": "TT",
  "America/Porto_Velho": "BR",
  "America/Puerto_Rico": "PR",
  "America/Punta_Arenas": "CL",
  "America/Rankin_Inlet": "CA",
  "America/Recife": "BR",
  "America/Regina": "CA",
  "America/Resolute": "CA",
  "America/Rio_Branco": "BR",
  "America/Santarem": "BR",
  "America/Santiago": "CL",
  "America/Santo_Domingo": "DO",
  "America/Sao_Paulo": "BR",
  "America/Scoresbysund": "GL",
  "America/Sitka": "US",
  "America/St_Barthelemy": "BL",
  "America/St_Johns": "CA",
  "America/St_Kitts": "KN",
  "America/St_Lucia": "LC",
  "America/St_Thomas": "VI",
  "America/St_Vincent": "VC",
  "America/Swift_Current": "CA",
  "America/Tegucigalpa": "HN",
  "America/Thule": "GL",
  "America/Tijuana": "MX",
  "America/Toronto": "CA",
  "America/Tortola": "VG",
  "America/Vancouver": "CA",
  "America/Whitehorse": "CA",
  "America/Winnipeg": "CA",
  "America/Yakutat": "US",
  "Antarctica/Casey": "AQ",
  "Antarctica/Davis": "AQ",
  "Antarctica/DumontDUrville": "AQ",
  "Antarctica/Macquarie": "AU",
  "Antarctica/Mawson": "AQ",
  "Antarctica/McMurdo": "AQ",
  "Antarctica/Palmer": "AQ",
  "Antarctica/Rothera": "AQ",
  "Antarctica/Syowa": "AQ",
  "Antarctica/Troll": "AQ",
  "Antarctica/Vostok": "AQ",
  "Arctic/Longyearbyen": "SJ",
  "Asia/Aden": "YE",
  "Asia/Almaty": "KZ",
  "Asia/Amman": "JO",
  "Asia/Anadyr": "RU",
  "Asia/Aqtau": "KZ",
  "Asia/Aqtobe": "KZ",
  "Asia/Ashgabat": "TM",
  "Asia/Atyrau": "KZ",
  "Asia/Baghdad": "IQ",
  "Asia/Bahrain": "BH",
  "Asia/Baku": "AZ",
  "Asia/Bangkok": "TH",
  "Asia/Barnaul": "RU",
  "Asia/Beirut": "LB",
  "Asia/Bishkek": "KG",
  "Asia/Brunei": "BN",
  "Asia/Calcutta": "IN",
  "Asia/Chita": "RU",
  "Asia/Colombo": "LK",
  "Asia/Damascus": "SY",
  "Asia/Dhaka": "BD",
  "Asia/Dili": "TL",
  "Asia/Dubai": "AE",
  "Asia/Dushanbe": "TJ",
  "Asia/Famagusta": "CY",
  "Asia/Gaza": "PS",
  "Asia/Hebron": "PS",
  "Asia/Ho_Chi_Minh": "VN",
  "Asia/Hong_Kong": "HK",
  "Asia/Hovd": "MN",
  "Asia/Irkutsk": "RU",
  "Asia/Jakarta": "ID",
  "Asia/Jayapura": "ID",
  "Asia/Jerusalem": "IL",
  "Asia/Kabul": "AF",
  "Asia/Kamchatka": "RU",
  "Asia/Karachi": "PK",
  "Asia/Kathmandu": "NP",
  "Asia/Katmandu": "NP",
  "Asia/Khandyga": "RU",
  "Asia/Kolkata": "IN",
  "Asia/Krasnoyarsk": "RU",
  "Asia/Kuala_Lumpur": "MY",
  "Asia/Kuching": "MY",
  "Asia/Kuwait": "KW",
  "Asia/Macau": "MO",
  "Asia/Magadan": "RU",
  "Asia/Makassar": "ID",
  "Asia/Manila": "PH",
  "Asia/Muscat": "OM",
  "Asia/Nicosia": "CY",
  "Asia/Novokuznetsk": "RU",
  "Asia/Novosibirsk": "RU",
  "Asia/Omsk": "RU",
  "Asia/Oral": "KZ",
  "Asia/Phnom_Penh": "KH",
  "Asia/Pontianak": "ID",
  "Asia/Pyongyang": "KP",
  "Asia/Qatar": "QA",
  "Asia/Qostanay": "KZ",
  "Asia/Qyzylorda": "KZ",
  "Asia/Rangoon": "MM",
  "Asia/Riyadh": "SA",
  "Asia/Saigon": "VN",
  "Asia/Sakhalin": "RU",
  "Asia/Samarkand": "UZ",
  "Asia/Seoul": "KR",
  "Asia/Shanghai": "CN",
  "Asia/Singapore": "SG",
  "Asia/Srednekolymsk": "RU",
  "Asia/Taipei": "TW",
  "Asia/Tashkent": "UZ",
  "Asia/Tbilisi": "GE",
  "Asia/Tehran": "IR",
  "Asia/Thimphu": "BT",
  "Asia/Tokyo": "JP",
  "Asia/Tomsk": "RU",
  "Asia/Ulaanbaatar": "MN",
  "Asia/Urumqi": "CN",
  "Asia/Ust-Nera": "RU",
  "Asia/Vientiane": "LA",
  "Asia/Vladivostok": "RU",
  "Asia/Yakutsk": "RU",
  "Asia/Yangon": "MM",
  "Asia/Yekaterinburg": "RU",
  "Asia/Yerevan": "AM",
  "Atlantic/Azores": "PT",
  "Atlantic/Bermuda": "BM",
  "Atlantic/Canary": "ES",
  "Atlantic/Cape_Verde": "CV",
  "Atlantic/Faeroe": "FO",
  "Atlantic/Faroe": "FO",
  "Atlantic/Madeira": "PT",
  "Atlantic/Reykjavik": "IS",
  "Atlantic/South_Georgia": "GS",
  "Atlantic/St_Helena": "SH",
  "Atlantic/Stanley": "FK",
  "Australia/Adelaide": "AU",
  "Australia/Brisbane": "AU",
  "Australia/Broken_Hill": "AU",
  "Australia/Darwin": "AU",
  "Australia/Eucla": "AU",
  "Australia/Hobart": "AU",
  "Australia/Lindeman": "AU",
  "Australia/Lord_Howe": "AU",
  "Australia/Melbourne": "AU",
  "Australia/Perth": "AU",
  "Australia/Sydney": "AU",
  "Europe/Amsterdam": "NL",
  "Europe/Andorra": "AD",
  "Europe/Astrakhan": "RU",
  "Europe/Athens": "GR",
  "Europe/Belgrade": "RS",
  "Europe/Berlin": "DE",
  "Europe/Bratislava": "SK",
  "Europe/Brussels": "BE",
  "Europe/Bucharest": "RO",
  "Europe/Budapest": "HU",
  "Europe/Busingen": "DE",
  "Europe/Chisinau": "MD",
  "Europe/Copenhagen": "DK",
  "Europe/Dublin": "IE",
  "Europe/Gibraltar": "GI",
  "Europe/Guernsey": "GG",
  "Europe/Helsinki": "FI",
  "Europe/Isle_of_Man": "IM",
  "Europe/Istanbul": "TR",
  "Europe/Jersey": "JE",
  "Europe/Kaliningrad": "RU",
  "Europe/Kiev": "UA",
  "Europe/Kirov": "RU",
  "Europe/Kyiv": "UA",
  "Europe/Lisbon": "PT",
  "Europe/Ljubljana": "SI",
  "Europe/London": "GB",
  "Europe/Luxembourg": "LU",
  "Europe/Madrid": "ES",
  "Europe/Malta": "MT",
  "Europe/Mariehamn": "AX",
  "Europe/Minsk": "BY",
  "Europe/Monaco": "MC",
  "Europe/Moscow": "RU",
  "Europe/Oslo": "NO",
  "Europe/Paris": "FR",
  "Europe/Podgorica": "ME",
  "Europe/Prague": "CZ",
  "Europe/Riga": "LV",
  "Europe/Rome": "IT",
  "Europe/Samara": "RU",
  "Europe/San_Marino": "SM",
  "Europe/Sarajevo": "BA",
  "Europe/Saratov": "RU",
  "Europe/Simferopol": "UA",
  "Europe/Skopje": "MK",
  "Europe/Sofia": "BG",
  "Europe/Stockholm": "SE",
  "Europe/Tallinn": "EE",
  "Europe/Tirane": "AL",
  "Europe/Ulyanovsk": "RU",
  "Europe/Vaduz": "LI",
  "Europe/Vatican": "VA",
  "Europe/Vienna": "AT",
  "Europe/Vilnius": "LT",
  "Europe/Volgograd": "RU",
  "Europe/Warsaw": "PL",
  "Europe/Zagreb": "HR",
  "Europe/Zurich": "CH",
  "Indian/Antananarivo": "MG",
  "Indian/Chagos": "IO",
  "Indian/Christmas": "CX",
  "Indian/Cocos": "CC",
  "Indian/Comoro": "KM",
  "Indian/Kerguelen": "TF",
  "Indian/Mahe": "SC",
  "Indian/Maldives": "MV",
  "Indian/Mauritius": "MU",
  "Indian/Mayotte": "YT",
  "Indian/Reunion": "RE",
  "Pacific/Apia": "WS",
  "Pacific/Auckland": "NZ",
  "Pacific/Bougainville": "PG",
  "Pacific/Chatham": "NZ",
  "Pacific/Chuuk": "FM",
  "Pacific/Easter": "CL",
  "Pacific/Efate": "VU",
  "Pacific/Fakaofo": "TK",
  "Pacific/Fiji": "FJ",
  "Pacific/Funafuti": "TV",
  "Pacific/Galapagos": "EC",
  "Pacific/Gambier": "PF",
  "Pacific/Guadalcanal": "SB",
  "Pacific/Guam": "GU",
  "Pacific/Honolulu": "US",
  "Pacific/Kanton": "KI",
  "Pacific/Kiritimati": "KI",
  "Pacific/Kosrae": "FM",
  "Pacific/Kwajalein": "MH",
  "Pacific/Majuro": "MH",
  "Pacific/Marquesas": "PF",
  "Pacific/Midway": "UM",
  "Pacific/Nauru": "NR",
  "Pacific/Niue": "NU",
  "Pacific/Norfolk": "NF",
  "Pacific/Noumea": "NC",
  "Pacific/Pago_Pago": "AS",
  "Pacific/Palau": "PW",
  "Pacific/Pitcairn": "PN",
  "Pacific/Pohnpei": "FM",
  "Pacific/Port_Moresby": "PG",
  "Pacific/Rarotonga": "CK",
  "Pacific/Saipan": "MP",
  "Pacific/Tahiti": "PF",
  "Pacific/Tarawa": "KI",
  "Pacific/Tongatapu": "TO",
  "Pacific/Truk": "FM",
  "Pacific/Wake": "UM",
  "Pacific/Wallis": "WF"
};
